config/routes.rb
Foodogle::Application.routes.draw do

  devise_for :users

  resources :recipes

  resources :cuisines
  resources :ingredients

  get "pages/home"
  get "pages/contact"
  get "pages/about"

  root :to => "pages#home"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  belongs_to :cuisine
  has_many :ingredients, :dependent => :destroy
  accepts_nested_attributes_for :ingredients, :reject_if => lambda{|a| a[:ing_name].blank?}, :allow_destroy => true

  validates_associated :cuisine

  validates_presence_of :name
  validates_presence_of :cuisine_id
  validates_presence_of :description
  validates_presence_of :content

  validates_uniqueness_of :name, :message => "Already exists please use another name "
  validates_length_of :name, :within => 1..50
  validates_length_of :description, :within => 1..200


  def self.search(search)
    if search
      search_condition = "%" + search + "%"
      find(:all, :conditions => ['name ILIKE ? OR description ILIKE ? OR content ILIKE ?', search_condition, search_condition, search_condition], :order => "name")
    else
      scoped
    end
  end

  def self.cuisineSearch(search)
    if search
      find(:all, :conditions => {:cuisine_id => "#{search}"}, :order => "name")
    end
  end

end


# == Schema Information
#
# Table name: recipes
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :text
#  image_url   :string(255)
#  cuisine_id  :integer
#  created_at  :datetime
#  updated_at  :datetime
#  content     :text
#

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]

  # GET /recipes
  # GET /recipes.xml
  def index

   @recipes = Recipe.search(params[:search]).paginate(:page => params[:page], :per_page => 5)
   @recipes.sort! {|a, b| a.name <=> b.name}


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.xml
  def show
    @recipe = Recipe.find(params[:id])
    @cuisine = Cuisine.find(@recipe.cuisine_id)

    @ingredients = Ingredient.find(:all, :order => "ing_name", :conditions => { :recipe_id => @recipe.id})

    @ingredients.each do |i|
      puts i.ing_name.class
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.xml
  def new
    @recipe = Recipe.new
    @cuisines = Cuisine.find(:all, :order => 'title')

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  def create
  @recipe = Recipe.new(params[:recipe])
  @cuisines = Cuisine.find(:all, :order => 'title')
  @recipe.ingredients.build

    respond_to do |format|
       if @recipe.save
            format.html { redirect_to(@recipe, :notice => 'Recipe was successfully created.') }
            format.xml  { render :xml => @recipe, :status => :created, :location => @recipe }
       else
           format.html { render :action => "new" }
           format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
       end

     end
  end


end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <br/>
    <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
    </div>


  <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area(:description, :class => "desc", :cols => 5, :rows => 5)%>
  </div>

  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :cuisine_id %><br />
    <%= f.collection_select(:cuisine_id, @cuisines,:id,:title,{ :include_blank => true }) %>
    <p>
        Can't find the cuisine?
        <%= link_to 'You can add one here', new_cuisine_path %>
    </p>
  </div>

  <div class="field">
     <%= f.label "Ingredients" %>
  </div>

  <div class="fields">
    <% f.fields_for :ingredients do |builder| %>
    <% render "ingredient_fields", :f => builder %>
    <% end %>
    <%=link_to_add_fields "Add Ingredient", f, :ingredients %>
  </div>

  <br/>
  <br/>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area(:content, :class => "content") %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_ing_form.html.erb
<% form_tag(:controller => "recipes", :action => "create") do %>
  <%= text_area_tag(:ing_name, "Enter the ingredient", :size => "10x6") %><br />
  <%= submit_tag("Add") %>
<% end %>

app/views/recipes/_ingredient.html.erb
<% div_for ingredient do %>
<ul><%= ingredient.ing_name %></ul>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<p class="fields">
        <%= f.label :ing_name, "Name" %>
        <%= f.text_field :ing_name, :size => 20 %>
        <%= f.label :quantiy, " Quantity" %>
        <%= f.text_field :quantiy, :size => 10 %>
        <%= f.hidden_field :_destroy %>
        <%= link_to_function "remove", "remove_fields(this)"%> <br/>
</p>

app/views/recipes/index.html.erb
<h2> Click on the Recipe to view details </h2>
<br/>

<%= will_paginate %>

<% @recipes.each do |recipe| %>

  <table>
      <tr>
        <td class="recipeUrl" width = "1%"><%= image_tag(recipe.image_url, :weight => "100", :height => "100") %></td>
        <td class="recipeName" width = "15%"><h3><%= link_to recipe.name, recipe %></h3></td>
      <tr/>
  </table>

<% end %>
<br />
<%= will_paginate %><br/>

<h3>
  <%= link_to 'Add Recipe', new_recipe_path %>
</h3>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<html>
  <head>

    <%= javascript_include_tag "prototype" %>
  </head>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
   <h2>
      <%= @recipe.name %>
   </h2>
   <%= @recipe.description %>
</p>

<p>
  <%= image_tag(@recipe.image_url, :width => "200", :height => "200") %>
</p>
<p>
  <b>Cuisine:</b>
  <%= @cuisine.title %>
</p>

<p>
  <b> Ingredients: </b>
    <% @ingredients.each do |f| %>
    <table class="table">
        <tr>
            <td class="ingName" width= "15%"><%= f.ing_name%> </td>
            <td class="quantity" width= "30%"><%= f.quantiy %> </td>
        </tr>
    </table>
    <% end %>

<p>
  <b>Content:</b>
  <%= @recipe.content %>
</p>

<br/>
<g:plusone annotation="inline"></g:plusone>
<br/>
<br/>

<%= link_to 'Back', recipes_path %>