config/routes.rb
Foodogle::Application.routes.draw do

  devise_for :users

  resources :recipes

  resources :cuisines
  resources :ingredients

  get "pages/home"
  get "pages/contact"
  get "pages/about"

  root :to => "pages#home"

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base

  has_many :recipes,   :dependent => :destroy
  accepts_nested_attributes_for :recipes
  validates_presence_of :title
  validates_presence_of :description
  validates_uniqueness_of :title, :message => "The Cuisine already exists"

end

# == Schema Information
# == Schema Information
#
# Table name: cuisines
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :index]
  # GET /cuisines
  # GET /cuisines.xml
  def index
    @cuisines = Cuisine.find(:all, :order => 'title').paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cuisines }
    end
  end

  # GET /cuisines/1
  # GET /cuisines/1.xml
  def show
    @cuisine = Cuisine.find(params[:id])
    @recipes = Recipe.cuisineSearch(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cuisine }
    end
  end

  # GET /cuisines/new
  # GET /cuisines/new.xml
  def new
    @cuisine = Cuisine.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cuisine }
    end
  end

  # GET /cuisines/1/edit
  def edit
    @cuisine = Cuisine.find(params[:id])
  end

  # POST /cuisines
  # POST /cuisines.xml
  def create
    @cuisine = Cuisine.new(params[:cuisine])

    respond_to do |format|
      if @cuisine.save
        format.html { redirect_to(@cuisine, :notice => 'Cuisine was successfully created.') }
        format.xml  { render :xml => @cuisine, :status => :created, :location => @cuisine }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cuisine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cuisines/1
  # PUT /cuisines/1.xml
  def update
    @cuisine = Cuisine.find(params[:id])

    respond_to do |format|
      if @cuisine.update_attributes(params[:cuisine])
        format.html { redirect_to(@cuisine, :notice => 'Cuisine was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cuisine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cuisines/1
  # DELETE /cuisines/1.xml
  def destroy
    @cuisine = Cuisine.find(params[:id])
    @cuisine.destroy

    respond_to do |format|
      format.html { redirect_to(cuisines_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/views/cuisines/_form.html.erb
<%= form_for(@cuisine) do |f| %>
  <% if @cuisine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cuisine.errors.count, "error") %> prohibited this cuisine from being saved:</h2>

      <ul>
      <% @cuisine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cuisines/edit.html.erb
<h1>Editing cuisine</h1>

<%= render 'form' %>

<%= link_to 'Show', @cuisine %> |
<%= link_to 'Back', cuisines_path %>

app/views/cuisines/index.html.erb
<h2>Cuisines</h2>
<br/>

<td>
    <%= will_paginate %>

    <div id="cuisines">

    <% @cuisines.each do |cuisine| %>
           <ul>
            <td><h3><%= link_to cuisine.title, cuisine %></h3></td>
           </ul>

    <% end %>


 </div>


<%= will_paginate %>
</table>

<br />

<%= link_to 'Add a Cuisine', new_cuisine_path %>

app/views/cuisines/new.html.erb
<h1>New Cuisine</h1>

<%= render 'form' %>

<%= link_to 'Back', cuisines_path %>

app/views/cuisines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><%= @cuisine.title %></h2>
</p>

<p>
  <b>Description:</b>
  <%= @cuisine.description %>
</p>

<% if @recipes.any? %>
    <p>
       <b><h4> Related recipes: </h4></b>
       <% @recipes.each do |recipe|%>
            <table>
                <tr>
                <td class="recipeUrl" width = "1%"><%= image_tag(recipe.image_url, :weight => "100", :height => "100") %></td>
                <td class="recipeName" width = "15%"><h3><%= link_to recipe.name, recipe %></h3></td>
                <tr/>
            </table>

       <% end %>
    </p>
<% end%>

<%= link_to 'Edit', edit_cuisine_path(@cuisine) %> |
<%= link_to 'Back', cuisines_path %>