config/routes.rb
Foodogle::Application.routes.draw do

  devise_for :users

  resources :recipes

  resources :cuisines
  resources :ingredients

  get "pages/home"
  get "pages/contact"
  get "pages/about"

  root :to => "pages#home"

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe, :foreign_key => "recipe_id"

  def self.my_search(search_items, search_type)
    last_element = search_items.last
    search_condition = " "

    search_items.each do |si|
      if si
        search_condition = search_condition + "ing_name ILIKE '%#{si}%'"
        if si != last_element
          search_condition = search_condition + " " + search_type + " "
        end
      end
    end

    where (search_condition)

  end
end


# == Schema Information
#
# Table name: ingredients
#
#  id         :integer         not null, primary key
#  ing_name   :string(255)
#  recipe_id  :integer
#  created_at :datetime
#  updated_at :datetime
#  quantiy    :string(255)
#

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController


  def index

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def create

    @recipes = []
    @search_strings = []
    @search_type = "OR"

    if params[:search_1] != ""
      @search_strings << params[:search_1]
    end

     if params[:search_2] != ""
      @search_strings << params[:search_2]
    end

     if params[:search_3] != ""
      @search_strings << params[:search_3]
    end

     if params[:search_4] != ""
      @search_strings << params[:search_4]
     end

    @ingredients = Ingredient.my_search(@search_strings, @search_type)
    @ingredients.each do |ingredient|
        @recipe = Recipe.find(ingredient.recipe_id)

        if @recipes.index(@recipe) == nil
           @recipes << @recipe
        end

    end

    respond_to do |format|
        format.html # create.html.erb
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @cuisine = Cuisine.find(@recipe.cuisine_id)

    @ingredients = Ingredient.find(:all, :conditions => { :recipe_id => @recipe.id})

    respond_to do |format|
      format.html # show.html.erb
    end
  end

end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_ingredient_fields.html.erb
<p class="fields">
        <%= f.label :ing_name, "Name" %>
        <%= f.text_field :ing_name, :size => 40 %>
        <%= f.hidden_field :_destroy %>
        <%= link_to_function "remove", "remove_fields(this)"%> <br/>
</p>

app/views/ingredients/create.html.erb
<% if @recipes.length == 0 %>
    <div id="error_explanation">
         <h3>Could not find any recipes matching your search ! </h2>
    </div>
<%else%>
    <h2> Recipes found with
        <% @i = 0 %>
        <%@search_strings.each do|ing| %>
            <%= ing %>
            <% @i = @i + 1 %>
            <% if (@i < (@search_strings.length) - 1)%>
                ,
            <% elsif (@i == (@search_strings.length) - 1) %>
                and
            <% else %>
                :
            <%end%>
        <%end%>
    </h2>

    <% @recipes.each do |recipe| %>
       <ul>
        <table>
          <tr>
            <td class "recipeName" width = "5%"><%= link_to recipe.name, :controller => 'ingredients', :action => 'show', :id => recipe.id  %>  </td>
            <td class="recipeUrl" width = "10%"><%= image_tag(recipe.image_url, :weight => "100", :height => "100") %></td>
          </tr>
        </table>
       </ul>
    <% end %>
<% end %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h2>Enter the ingredients </h2>
<br/>
<div id="searchIng" >
     <%= form_for ingredients_path, :method => 'get', :action => 'create' do %>
     <p>
        <%= text_field_tag :search_1, params[:search_1]%>   <br/>
        <%= text_field_tag :search_2, params[:search_2]%>   <br/>
        <%= text_field_tag :search_3, params[:search_3]%>   <br/>
        <%= text_field_tag :search_4, params[:search_4]%>   <br/>
        <%= submit_tag "Search", :name => nil %>
     </p>
     <% end %>
</div>
<br/>
<%= image_tag("pic1.jpg", :width => "500", :height => "300") %>

app/views/ingredients/show.html.erb
<p id="notice">
    <%= notice %>
</p>

<p>
  <b>Name:</b>
  <%= @recipe.name %>
  <br/>
  <%= @recipe.description %>
</p>
<p>
  <b>Image url:</b>
  <%= image_tag(@recipe.image_url, :weight => "200", :height => "200") %>
</p>

<p>
  <b>Cuisine:</b>
  <%= @cuisine.title %>
</p>

<p>
<b> Ingredients: </b>
    <% @ingredients.each do |f| %>
    <%= f.ing_name %>
    <% end %>
</p>

<p>
  <b>Content:</b>
  <%= @recipe.content %>
</p>

<br/>
  <g:plusone annotation="inline"></g:plusone>